name: ci

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test-change-tag-line:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v3

      - name: change the tag line of the text file
        uses: Balou9/change-tag-line@v0.2.0-beta
        with:
          file-path: ./test_files/one.txt

      - name: observe directory
        run: |
          ls

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GHUB_TOKEN }}'
          email: 'eto.owosekun@gmail.com'
          actor: 'Balou9'
      - run: |
          git remote add origin-cc https://github.com/Balou9/use-change-tag-line.git

          git add .
          git commit -m "chore: adds modified text file"

          git push origin-cc main