name: ci

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-push-text-file-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Change the tag line of the text file
        uses: Balou9/change-tag-line@v0.2.0-beta
        with:
          file-path: ./test_files/one.txt

      - name: Set git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GHUB_TOKEN }}
          email: eto.owosekun@gmail.com
          actor: ${{ github.actor }}

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "chore: adds modified text file"
          git push origin main

      - name: Build docker image
        run: |
          docker build . \
          --tag ghcr.io/balou9/use-change-tag-line:modified-text-file
      
      - name: Login to github container registry
        run: |
          echo "${{ secrets.GHUB_TOKEN }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to github container registry
        run: |
          docker push ghcr.io/balou9/use-change-tag-line:modified-text-file

      - name: Logs out from github container registry
        run: |
          docker logout ghcr.io

      - name: Post clean up - Removes text file and commit and push changes
        run: |
          rm output.txt
          git add .
          git commit -m "chore: adds modified text file"
          git push origin main