name: ci

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test-change-tag-line:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v3

      - name: change the tag line of the text file
        uses: Balou9/change-tag-line@v0.2.0-beta
        with:
          file-path: ./test_files/one.txt

      - name: observe directory
        run: |
          ls

      - name: configure git with access token 
        run: |
          git config user.name 'Balou9'
          git config user.email 'eto.owosekun@gmail.com'
          git remote add origin "https://$GITHUB_USERNAME:${{ secrets.GH_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"

      - name: Add changes (if applicable)
        run: |
          git add .
          git commit -m "chore: adds modified text file"

      - name: Push changes
        run: git push origin main