name: ci

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-push-text-file-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Change the tag line of the text file
        uses: Balou9/change-tag-line@v0.2.0-beta
        with:
          file-path: ./test_files/one.txt

      - name: Observe directory (Checks if the output txt file exist)
        run: |
          ls

      - name: Set git credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GHUB_TOKEN }}
          email: eto.owosekun@gmail.com
          actor: ${{ github.actor }}

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "chore: adds modified text file"
          git push origin main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: balou9/modified-text-files:latest
          github-token: ${{ secrets.GHUB_TOKEN }}