name: ci

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test-change-tag-line:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v3

      - name: change the tag line of the text file
        uses: Balou9/change-tag-line
        with:
          file-path: ./test_files/one.txt